# root compose file. This will be started via docker compose up -d. It then starts everything else aswell

include:
  # base services
  - base/caddy/compose.yml
  - base/postgres/compose.yml
  - base/portainer/compose.yml
  - base/redis/compose.yml
  # services
  - service/kavita/compose.yml
  - service/commafeed/compose.yml
  - service/pelican/compose.yml
  - service/affine/compose.yml

networks:
  edge:
  db:
  local:
