services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    restart: unless-stopped
    environment:
      - PUID: 1000
      - PGID: 1000
      - TZ: CET
    volumes:
      - data/:/data/
      - config/:/config/
    networks: 
      - edge

