x-common:
  panel:
    &panel-environment
    APP_URL: "https://panel.geroxus.net"
    APP_TIMEZONE: "CET"
    APP_SERVICE_AUTHOR: "admin@geroxus.net"
    ADMIN_EMAIL: "admin@geroxus.net"
  mail:
    &mail-environment
    MAIL_FROM: "noreply@geroxus.net"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

services:
  panel:
    image: ghcr.io/pelican-dev/panel:latest
    container_name: panel
    restart: unless-stopped
    networks:
      db:
      edge:
    volumes:
      - ./data/panel/var/:/pelican-data/
      - ./data/panel/logs/:/var/www/html/storage/logs/
    environment:
      <<: [*panel-environment, *mail-environment]
      XDG_DATA_HOME: "/pelican-data"
      BEHIND_PROXY: "true"
      DB_PASSWORD: ${DB_PASSWORD_PELICAN_PANEL}
    depends_on:
      - database

